Install npm packages as needed by meteor.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -146,6 +146,16 @@ HOME="$VENDORED_METEOR" "$VENDORED_METEOR"/.meteor/meteor bundle $METEOR_RELEASE
 mkdir -p "$METEOR_BUILD_DIR"/app
 tar -zxf "$CACHE_DIR"/bundle.tar.gz --strip-components 1 -C "$METEOR_BUILD_DIR"/app
 rm "$CACHE_DIR"/bundle.tar.gz
+
+echo "Installing npm packages" | indent
+cd $METEOR_BUILD_DIR/programs/server
+HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NODE/bin/npm install 2>&1 | indent
+
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to $command dependencies with npm"
+  exit 1
+fi
+
 ############################################
 
 ############################################
